+
H2O
Base mass
H2O1
X
Xxx
Unknown
C6H8N1O1
A
Ala
Alanine
C3H5N1O1
C
Cys
Cysteine
C3H4N1O1S1
D
Asp
Asp. acid
C4H5N1O3
E
Glu
Glu. acid
C5H7N1O3
F
Phe
Phenylala.
C9H9N1O1
G
Gly
Glycine
C2H3N1O1
H
His
Histidine
C6H7N3O1
I
Ile
Isoleu.
C6H11N1O1
K
Lys
Lysine
C6H12N2O1
L
Leu
Leucine
C6H11N1O1
M
Met
Methionine
C5H9N1O1S1
N
Asn
Asparagine
C4H6N2O2
P
Pro
Proline
C5H7N1O1
Q
Gln
Glutamine
C5H8N2O2
R
Arg
Arginine
C6H12N4O1
S
Ser
Serine
C3H5N1O2
T
Thr
Threonine
C4H7N1O2
V
Val
Valine
C5H9N1O1
W
Trp
Tryptopha.
C11H10N2O1
Y
Tyr
Tyrosine
C9H9N1O2
B
Bbb
Unknown

U
Uuu
Xane
C9H9N1O2
Z
Zzz
Unknown

Æ
Æææ
Unknown

Ø
Øøø
Unknown

Å
Ååå
Unknown

¤
¤¤¤
Unknown

Û
Ûüü
Unknown

ß
ßßß
Unknown

1
111
Unknown

2
222
Unknown

-
---
Split
H2O1
